name: Main job

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  GCP_PROJECT_ID: seed-zero
  GCP_SERVICE_ACCOUNT: githubdeploy@seed-zero.iam.gserviceaccount.com
  GCP_SA_KEY: publish.json
  SERVICE_NAME: ${{ github.event.repository.name }}
  SERVICE_REGION: asia-southeast1

jobs:
  deploy-main:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: $GCP_SA_KEY
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Use gcloud CLI
        run: |
          gcloud run deploy $SERVICE_NAME \
          --quiet \
          --set-env-vars="NAME=starter-code" \
          --region $SERVICE_REGION \
          --source . \
          --project $GCP_PROJECT_ID \
          --labels "commit-sha=${{ github.sha }}" \
          --service-account $GCP_SERVICE_ACCOUNT
      - name: Config policy to allow unauthenticated
        run: |
          gcloud run services add-iam-policy-binding $SERVICE_NAME \
          --quiet \
          --region $SERVICE_REGION \
          --member="allUsers" \
          --role="roles/run.invoker"
