name: Main job

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  GCP_PROJECT_ID: seed-zero
  GCP_SERVICE_ACCOUNT: githubdeploy@seed-zero.iam.gserviceaccount.com
  GCP_SA_KEY: |
{
  "type": "service_account",
  "project_id": "seed-zero",
  "private_key_id": "87ceab1abd9d86f0c4d1c59fa6696cc439cb0ba0",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwKi/tk12AL9Kb\n7mNE4Dk6kTeIMkkxQPZlTceBpJIOUt6QNG5ZqpJV8a0TOxLFuyGOJ+47pdC3tTYT\ndIEVAYiHJsUYrQHGc4YmIkegXSTmFSdwFFFl0uaUwQEuNf10M4LyrrUVWofjk5bb\nh4HSXObd+YlVLRjDe5LahoISf0GB8n4KoNd05YhZSvDHJ0N3+c2ALNaWG8ARWQ6a\nfWSF9KhmrQaMij1vTRrBkZnvmjA2cGrEoA0FAjjPJS6bqU/LKvSs+IQTADlWpgD8\ns7NAKQAswHo8bYAcXEcT54YAV5Bor9gM8mZXYpuAoCszjY+R0sNdLSjXWvgzcjsq\nV/AZBEKDAgMBAAECggEAVdbYr80E3HdxCmYonOEdQbqM8qJ+I6/h4A78TeGhAbXD\nmUTTGIIS+CnhCePZC9xZR2mRniL4BuwXw3cbht7OZfywQYvbt5WHIoHFoRCB8FMS\nenyMBS+1B3rcVmYccEjBX/tdZWBNosjB04q96YE3RaZYEtb8oBRQxIaSTu0PQH/X\nL9U/0Jf1rM8hAAncTuC2tolJKiAMpqPl19roDb13YTa6IRS6ZQJdtXX78Cl2iFYU\niqw5b+J2Mp1TRde7OXk2KzQMtLHE2KJoKaL3fPqGBkxMM92IEqFXpll/+kDQkZ+B\n027FCD+RfQzcUueqRuM520Z/OzKZHF1h58HsKxPPoQKBgQDhqByFfWloGyFkVREd\niJugKZt/mirvua1Et7q/pSrEmzRMsDTYZmgAIr3jrsnP17Gi6YZRviLVXlsJMOre\nLU0SF4yAcZT7gwMjTLMKU80bjIt8tJMom1VL8kw28NYm8yNWzhRsJjoiMr4vUkJy\n/C9H/FK6zOHeeG8WjoIpeWnOeQKBgQDH2mSDbhVR2+e8AaPD95GQ/VwYqxebjlr+\nfgS/xsE5FdUEgx5jsKirapwZGIswLSJOk2Diq1ISg1f92qFyjY6/rSYsw/NJKKph\nC8yC5K3UfW2+T5xsL3SpNGuXf/y3N07QZK8waF8FPGNLrbL24ufr0HDIraSYgyYs\nT75WDBlp2wKBgQDhXhGmLHuScs4ls2PVmDK9gfCAP0u0gj+PSuPjNSUCmHNiR/Vv\nTs99mzUE6PM7dhM+PnZcu0V0zbij9EwNuzam5Af52/ZMPytqHNcPcGR/qB1DXeE/\nA+vrXsFJebyXx+q6bjUtUfxrXTxebIxa5IygG1vQnoDSvHtODuPmYhEPGQKBgCJ3\n2RQN3WFz4uC7C6qVvSZbfBHJGFY81BbGVz1YIyUcTdPsZUZeRojh5zAw2nihoCQb\nKP+O+qW0v21J0sR2A6OtUkMwPHpmqBP6u/frRsu6Ij5Lbrf960nvf4ruiQB0aoRo\niQp5RcIaaym3OIF6GvPBzGHgCN5A6EmGK1ad2Zg3AoGBANTo0wK+rd5T4G+knpBr\nmRaCy+FzMH5u9FP0lxIDaq8NFA6jezqqLv/iuDq7ywbr37Lmr0pVHH9AfcsWlKcL\nD5wAaDNhWZaCQ4cMH+4I8YT/WYucZ7v6aacYRoQoIkEa+/k9BpF4GNjcQix27mIT\nak7Au66iLqERivDJkMnzbyZC\n-----END PRIVATE KEY-----\n",
  "client_email": "githubdeploy@seed-zero.iam.gserviceaccount.com",
  "client_id": "102943534705601907734",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/githubdeploy%40seed-zero.iam.gserviceaccount.com"
}
  GCP_SA_FILE: publish.json
  SERVICE_NAME: ${{ github.event.repository.name }}
  SERVICE_REGION: asia-southeast1

jobs:
  deploy-main:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: seed-zero
          service_account_key: $GCP_SA_KEY
          export_default_credentials: true
      - name: Use gcloud CLI
        run: |
          gcloud run deploy $SERVICE_NAME \
          --quiet \
          --set-env-vars="NAME=starter-code" \
          --region $SERVICE_REGION \
          --source . \
          --project $GCP_PROJECT_ID \
          --labels "commit-sha=${{ github.sha }}" \
          --service-account $GCP_SERVICE_ACCOUNT
      - name: Config policy to allow unauthenticated
        run: |
          gcloud run services add-iam-policy-binding $SERVICE_NAME \
          --quiet \
          --region $SERVICE_REGION \
          --member="allUsers" \
          --role="roles/run.invoker"
